version: 2

updates:
  # Keep Docker base images (e.g., alpine) up to date
  - package-ecosystem: "docker"
    directory: "/fargate/exampletask"
    schedule:
      interval: "weekly"

  # Enable this once you add GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
